In [ ]:
#Name: Achyutha Nagaveti Bhavani Santhoshi
#CWID: A20314248
#Course: CS 5683: Big Data Analytics
#Assignment: Assignment-3

# CS 5683 - Big Data Analytics
## Assignment - 3: SVD and PCA

In [ ]:
# Import packages here
import numpy as np
from numpy import array
from sklearn.decomposition import PCA
from scipy.linalg import svd
from scipy import linalg
from scipy.linalg import eigh

##### Consider the following list as a simple matrix 'M' for all tasks of this assignment

In [ ]:
M = [[1,2],[3,4],[5,6],[7,8]] # Convert this list to a matrix

In [ ]:
M = np.array(M)
print(M)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


##### Question-1: Compute SVD of M

In [ ]:
# Use Python's scipy.linalg.svd function 
# and set the argument full_matrices to False



Report the values of $ U $, $ \sum $ and $ V^T $ from SVD of M in the below cell

NOTE: Values of $ \sum $ should be in decreasing order - first element should be greater than the second element, and so on

In [ ]:
U, s, VT = svd(M)
print("𝑈")
print(U)
print("∑")
print(s)
print("𝑉𝑇")
print(VT)

𝑈
[[-0.15248323 -0.82264747 -0.39450102 -0.37995913]
 [-0.34991837 -0.42137529  0.24279655  0.80065588]
 [-0.54735351 -0.0201031   0.69790998 -0.46143436]
 [-0.74478865  0.38116908 -0.5462055   0.04073761]]
∑
[14.2690955   0.62682823]
𝑉𝑇
[[-0.64142303 -0.7671874 ]
 [ 0.7671874  -0.64142303]]


In [ ]:
v= np.transpose(VT)
print("V")
print(v)

V
[[-0.64142303  0.7671874 ]
 [-0.7671874  -0.64142303]]


##### Question-2: Compute Eigen Decomposition

We do Eigen Decomposition on $ M^TM $

In [ ]:
# Use Python's scipy.linalg.eigh function


Report Eigenvalues(Evals) and Eigenvectors-matrix(Evecs) from the above function in the below cell

NOTE: Make sure Evals are in decreasing order and Eigenvectors in Evecs correspond to that of sorted Eigenvalues in Evecs

In [ ]:
w, v = eigh(np.matmul(M.transpose(),M))
idx = w.argsort()[::-1]   
evals = w[idx]
evecs = v[:,idx]
print("Eigenvalues")
print(evals)
print("Eigenvectors-matrix")
print(evecs)

Eigenvalues
[203.60708637   0.39291363]
Eigenvectors-matrix
[[ 0.64142303 -0.7671874 ]
 [ 0.7671874   0.64142303]]


##### Question-3: V Vs. Evecs (2 Points)

What is the correspondence between **$ V $** from scipy.linalg.svd function and **Evecs** from scipy.linalg.eigh function? Write your answer in the below cell.

NOTE: scipy.linalg.svd function returns $ V^T $ not $ V $

In [ ]:
SVD is the decomposition of a matrix M into 3 matrices – U, S, and V
Eigen is the decomposition of a matrix M Decomposition on  𝑀𝑇𝑀

The correspondence between  𝑉  from scipy.linalg.svd function and Evecs from scipy.linalg.eigh function is:

The 𝑉 Evecs from scipy.linalg.eigh function is the negative multiplication of from scipy.linalg.svd

##### Question-4 Sigma Vs. EVals (2 Points)

What is the correspondence between **$ \sum $** from scipy.linalg.svd function and **Evals** from scipy.linalg.eigh function? Write your answer in the below cell.

In [ ]:
SVD is the decomposition of a matrix M into 3 matrices – U, S, and V
Eigen is the decomposition of a matrix M Decomposition on  𝑀𝑇𝑀

The correspondence between ∑  from scipy.linalg.svd function and Evals from scipy.linalg.eigh function is:

The ∑ from scipy.linalg.svd functio is the square root of Evals from scipy.linalg.eigh function

##### Question-5: Do you think we can achieve PCA with SVD? If so, how? (2 Points)

In [ ]:

PCA and SVD are closely related approaches and can be both applied to decompose any rectangular matrices

Their relationship by performing SVD on the covariance matrix M:

M = SVDT SVD / n - 1
  = UT∑V VT∑U / n - 1
  = V (pow(∑,2) / n - 1) VT
  = V (pow(∑,2) / n - 1) pow(V, -1) {because V is unitary}
  = pow(∑,2) / n - 1


Yes, We can achieve PCA with SVD but we should truncate some values to achieve the result.

